-- MySQL Script generated by MySQL Workbench
-- Thu Nov  3 22:20:12 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Mascotas
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Mascotas` ;

-- -----------------------------------------------------
-- Schema Mascotas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Mascotas` DEFAULT CHARACTER SET utf8 ;
USE `Mascotas` ;

-- -----------------------------------------------------
-- Table `Mascotas`.`comunidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Mascotas`.`comunidad` (
  `id_comunidad` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id_comunidad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Mascotas`.`peluquerias_caninas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Mascotas`.`peluquerias_caninas` (
  `id_peluqueria` INT NOT NULL AUTO_INCREMENT,
  `nombre_peluqueria` VARCHAR(45) NOT NULL,
  `nombre_usuario` VARCHAR(45) NOT NULL,
  `clave` VARCHAR(45) NOT NULL,
  `pais` VARCHAR(45) NULL,
  `provincia` VARCHAR(45) NULL,
  `localidad` VARCHAR(45) NULL,
  `calle` VARCHAR(45) NULL,
  `numero` INT NULL,
  `productos` VARCHAR(45) NULL,
  `servicios` VARCHAR(45) NULL,
  `mail` VARCHAR(45) NOT NULL,
  `id_comunidadFK` INT NULL,
  PRIMARY KEY (`id_peluqueria`),
  CONSTRAINT `id_comunidadFK`
    FOREIGN KEY (`id_comunidadFK`)
    REFERENCES `Mascotas`.`comunidad` (`id_comunidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `id_comunidadFK_idx` ON `Mascotas`.`peluquerias_caninas` (`id_comunidadFK` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Mascotas`.`dueno_mascotas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Mascotas`.`dueno_mascotas` (
  `id_dueno` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `nombre_usuario` VARCHAR(45) NOT NULL,
  `clave` VARCHAR(45) NOT NULL,
  `pais` VARCHAR(45) NULL,
  `provincia` VARCHAR(45) NULL,
  `localidad` VARCHAR(45) NULL,
  `calle` VARCHAR(45) NULL,
  `numero` INT NULL,
  `tel` INT NOT NULL,
  `mail` VARCHAR(45) NOT NULL,
  `id_comunidadFK` INT NULL,
  PRIMARY KEY (`id_dueno`),
  CONSTRAINT `id_comunidadFK`
    FOREIGN KEY (`id_comunidadFK`)
    REFERENCES `Mascotas`.`comunidad` (`id_comunidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `id_comunidadFK_idx` ON `Mascotas`.`dueno_mascotas` (`id_comunidadFK` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Mascotas`.`veterinarias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Mascotas`.`veterinarias` (
  `id_veterinaria` INT NOT NULL AUTO_INCREMENT,
  `nombre_veterinaria` VARCHAR(45) NOT NULL,
  `nombre_usuario` VARCHAR(45) NOT NULL,
  `clave` VARCHAR(45) NOT NULL,
  `pais` VARCHAR(45) NULL,
  `provincia` VARCHAR(45) NULL,
  `localidad` VARCHAR(45) NULL,
  `calle` VARCHAR(45) NULL,
  `numero` INT NULL,
  `productos` VARCHAR(45) NULL,
  `servicios` VARCHAR(45) NULL,
  `mail` VARCHAR(45) NOT NULL,
  `id_comunidadFK` INT NULL,
  PRIMARY KEY (`id_veterinaria`),
  CONSTRAINT `id_comunidadFK`
    FOREIGN KEY (`id_comunidadFK`)
    REFERENCES `Mascotas`.`comunidad` (`id_comunidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `id_comunidadFK_idx` ON `Mascotas`.`veterinarias` (`id_comunidadFK` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Mascotas`.`paseadores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Mascotas`.`paseadores` (
  `id_paseador` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `nombre_usuario` VARCHAR(45) NOT NULL,
  `clave` VARCHAR(45) NOT NULL,
  `pais` VARCHAR(45) NULL,
  `provincia` VARCHAR(45) NULL,
  `localidad` VARCHAR(45) NULL,
  `calle` VARCHAR(45) NULL,
  `numero` INT NULL,
  `servicios` VARCHAR(45) NULL,
  `mail` VARCHAR(45) NOT NULL,
  `id_comunidadFK` INT NULL,
  PRIMARY KEY (`id_paseador`),
  CONSTRAINT `id_comunidadFK`
    FOREIGN KEY (`id_comunidadFK`)
    REFERENCES `Mascotas`.`comunidad` (`id_comunidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `id_comunidadFK_idx` ON `Mascotas`.`paseadores` (`id_comunidadFK` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Mascotas`.`reservas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Mascotas`.`reservas` (
  `id_reserva` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NULL,
  `titulo` VARCHAR(45) NULL,
  `id_duenoFK` INT NULL,
  `id_peluqueriaFK` INT NULL,
  `id_veterinariaFK` INT NULL,
  `id_paseadorFK` INT NULL,
  PRIMARY KEY (`id_reserva`),
  CONSTRAINT `id_duenoFK`
    FOREIGN KEY (`id_duenoFK`)
    REFERENCES `Mascotas`.`dueno_mascotas` (`id_dueno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_peluqueriaFK`
    FOREIGN KEY (`id_peluqueriaFK`)
    REFERENCES `Mascotas`.`peluquerias_caninas` (`id_peluqueria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_veterinariaFK`
    FOREIGN KEY (`id_veterinariaFK`)
    REFERENCES `Mascotas`.`veterinarias` (`id_veterinaria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_paseadorFK`
    FOREIGN KEY (`id_paseadorFK`)
    REFERENCES `Mascotas`.`paseadores` (`id_paseador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `id_duenoFK_idx` ON `Mascotas`.`reservas` (`id_duenoFK` ASC) VISIBLE;

CREATE INDEX `id_peluqueriaFK_idx` ON `Mascotas`.`reservas` (`id_peluqueriaFK` ASC) VISIBLE;

CREATE INDEX `id_veterinariaFK_idx` ON `Mascotas`.`reservas` (`id_veterinariaFK` ASC) VISIBLE;

CREATE INDEX `id_paseadorFK_idx` ON `Mascotas`.`reservas` (`id_paseadorFK` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Mascotas`.`info_mascotas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Mascotas`.`info_mascotas` (
  `id_mascota` INT NOT NULL AUTO_INCREMENT,
  `especie_animal` VARCHAR(45) NULL,
  `raza` VARCHAR(45) NULL,
  `peso_recomendado` FLOAT NULL,
  `caracter` VARCHAR(400) NULL,
  `actividad_fisica` VARCHAR(45) NULL,
  `clima_recomendado` VARCHAR(45) NULL,
  `alimentacion` VARCHAR(200) NULL,
  `cuidados` VARCHAR(400) NULL,
  `esperanza_vida` VARCHAR(45) NULL,
  `patologia` VARCHAR(200) NULL,
  `vacunas` VARCHAR(200) NULL,
  PRIMARY KEY (`id_mascota`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Mascotas`.`registro_mascota`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Mascotas`.`registro_mascota` (
  `id_registro_mascota` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `nacimiento` DATE NULL,
  `especie_animal` VARCHAR(45) NOT NULL,
  `raza` VARCHAR(45) NULL,
  `peso` FLOAT NULL,
  `altura` FLOAT NULL,
  `patologia` VARCHAR(200) NULL,
  `id_duenoFK` INT NULL,
  `id_paseadorFK` INT NULL,
  `id_veterinariaFK` INT NULL,
  `id_peluqueriaFK` INT NULL,
  `id_mascotaFK` INT NULL,
  PRIMARY KEY (`id_registro_mascota`),
  CONSTRAINT `id_duenoFK`
    FOREIGN KEY (`id_duenoFK`)
    REFERENCES `Mascotas`.`dueno_mascotas` (`id_dueno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_veterinariaFK`
    FOREIGN KEY (`id_veterinariaFK`)
    REFERENCES `Mascotas`.`veterinarias` (`id_veterinaria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_peluqueriaFK`
    FOREIGN KEY (`id_peluqueriaFK`)
    REFERENCES `Mascotas`.`peluquerias_caninas` (`id_peluqueria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_paseadorFK`
    FOREIGN KEY (`id_paseadorFK`)
    REFERENCES `Mascotas`.`paseadores` (`id_paseador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_mascotaFK`
    FOREIGN KEY (`id_mascotaFK`)
    REFERENCES `Mascotas`.`info_mascotas` (`id_mascota`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `id_dueno_idx` ON `Mascotas`.`registro_mascota` (`id_duenoFK` ASC) VISIBLE;

CREATE INDEX `id_veterinariaFK_idx` ON `Mascotas`.`registro_mascota` (`id_veterinariaFK` ASC) VISIBLE;

CREATE INDEX `id_peluqueriaFK_idx` ON `Mascotas`.`registro_mascota` (`id_peluqueriaFK` ASC) VISIBLE;

CREATE INDEX `id_paseadorFK_idx` ON `Mascotas`.`registro_mascota` (`id_paseadorFK` ASC) VISIBLE;

CREATE INDEX `id_mascotaFK_idx` ON `Mascotas`.`registro_mascota` (`id_mascotaFK` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Mascotas`.`servicios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Mascotas`.`servicios` (
  `id_servicio` INT NOT NULL AUTO_INCREMENT,
  `servicio` VARCHAR(45) NULL,
  `adomicilio` VARCHAR(45) NULL,
  `cercanas` VARCHAR(45) NULL,
  `deguardia` VARCHAR(45) NULL,
  PRIMARY KEY (`id_servicio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Mascotas`.`posteos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Mascotas`.`posteos` (
  `id_posteo` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `contenido` VARCHAR(45) NOT NULL,
  `imagen` TINYINT(1) NULL,
  `comentarios` TEXT NULL,
  `fecha` DATETIME NULL,
  `id_duenoFK` INT NULL,
  `id_veterinariaFK` INT NULL,
  `id_paseadorFK` INT NULL,
  `id_peluqueriaFK` INT NULL,
  PRIMARY KEY (`id_posteo`),
  CONSTRAINT `id_duenoFK`
    FOREIGN KEY (`id_duenoFK`)
    REFERENCES `Mascotas`.`dueno_mascotas` (`id_dueno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_veterinariaFK`
    FOREIGN KEY (`id_veterinariaFK`)
    REFERENCES `Mascotas`.`veterinarias` (`id_veterinaria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_paseadorFK`
    FOREIGN KEY (`id_paseadorFK`)
    REFERENCES `Mascotas`.`paseadores` (`id_paseador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_peluqueriaFK`
    FOREIGN KEY (`id_peluqueriaFK`)
    REFERENCES `Mascotas`.`peluquerias_caninas` (`id_peluqueria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `id_duenoFK_idx` ON `Mascotas`.`posteos` (`id_duenoFK` ASC) VISIBLE;

CREATE INDEX `id_veterinariaFK_idx` ON `Mascotas`.`posteos` (`id_veterinariaFK` ASC) VISIBLE;

CREATE INDEX `id_paseadorFK_idx` ON `Mascotas`.`posteos` (`id_paseadorFK` ASC) VISIBLE;

CREATE INDEX `id_peluqueriaFK_idx` ON `Mascotas`.`posteos` (`id_peluqueriaFK` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Mascotas`.`grupos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Mascotas`.`grupos` (
  `id_grupo` INT NOT NULL AUTO_INCREMENT,
  `nombre_grupo` VARCHAR(45) NOT NULL,
  `titulo` VARCHAR(45) NULL,
  `contenido` VARCHAR(45) NULL,
  `imagen` TINYINT(1) NULL,
  `imagen_url` VARCHAR(800) NULL,
  `comentarios` TEXT NULL,
  `fecha` DATETIME NULL,
  `id_comunidadFK` INT NULL,
  PRIMARY KEY (`id_grupo`),
  CONSTRAINT `id_comunidadFK`
    FOREIGN KEY (`id_comunidadFK`)
    REFERENCES `Mascotas`.`comunidad` (`id_comunidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `id_comunidadFK_idx` ON `Mascotas`.`grupos` (`id_comunidadFK` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Mascotas`.`avatar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Mascotas`.`avatar` (
  `id_avatar` INT NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(800) NOT NULL,
  `id_duenoFK` INT NULL,
  `id_peluqueriaFK` INT NULL,
  `id_veterinariaFK` INT NULL,
  `id_paseadorFK` INT NULL,
  PRIMARY KEY (`id_avatar`),
  CONSTRAINT `id_duenoFK`
    FOREIGN KEY (`id_duenoFK`)
    REFERENCES `Mascotas`.`dueno_mascotas` (`id_dueno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_peluqueriaFK`
    FOREIGN KEY (`id_peluqueriaFK`)
    REFERENCES `Mascotas`.`peluquerias_caninas` (`id_peluqueria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_veterinariaFK`
    FOREIGN KEY (`id_veterinariaFK`)
    REFERENCES `Mascotas`.`veterinarias` (`id_veterinaria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_paseadorFK`
    FOREIGN KEY (`id_paseadorFK`)
    REFERENCES `Mascotas`.`paseadores` (`id_paseador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `id_duenoFK_idx` ON `Mascotas`.`avatar` (`id_duenoFK` ASC) VISIBLE;

CREATE INDEX `id_peluqueriaFK_idx` ON `Mascotas`.`avatar` (`id_peluqueriaFK` ASC) VISIBLE;

CREATE INDEX `id_veterinariaFK_idx` ON `Mascotas`.`avatar` (`id_veterinariaFK` ASC) VISIBLE;

CREATE INDEX `id_paseadorFK_idx` ON `Mascotas`.`avatar` (`id_paseadorFK` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Mascotas`.`peluquerias_dueno_mascota`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Mascotas`.`peluquerias_dueno_mascota` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_duenoFK` INT NULL,
  `id_peluqueriaFK` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `id_duenoFK`
    FOREIGN KEY (`id_duenoFK`)
    REFERENCES `Mascotas`.`dueno_mascotas` (`id_dueno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_peluqueriaFK`
    FOREIGN KEY (`id_peluqueriaFK`)
    REFERENCES `Mascotas`.`peluquerias_caninas` (`id_peluqueria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_peluquerias_dueno_mascota_dueno_idx` ON `Mascotas`.`peluquerias_dueno_mascota` (`id_duenoFK` ASC) VISIBLE;

CREATE INDEX `id_peluqueriaFK_idx` ON `Mascotas`.`peluquerias_dueno_mascota` (`id_peluqueriaFK` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Mascotas`.`veterinarias_dueno_mascotas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Mascotas`.`veterinarias_dueno_mascotas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_duenoFK` INT NULL,
  `id_veterinariaFK` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `id_duenoFK`
    FOREIGN KEY (`id_duenoFK`)
    REFERENCES `Mascotas`.`dueno_mascotas` (`id_dueno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_veterinariaFK`
    FOREIGN KEY (`id_veterinariaFK`)
    REFERENCES `Mascotas`.`veterinarias` (`id_veterinaria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `id_duenoFK_idx` ON `Mascotas`.`veterinarias_dueno_mascotas` (`id_duenoFK` ASC) VISIBLE;

CREATE INDEX `id_veterinariaFK_idx` ON `Mascotas`.`veterinarias_dueno_mascotas` (`id_veterinariaFK` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Mascotas`.`paseadores_dueno_mascotas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Mascotas`.`paseadores_dueno_mascotas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_duenoFK` INT NULL,
  `id_paseadorFK` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `id_duenoFK`
    FOREIGN KEY (`id_duenoFK`)
    REFERENCES `Mascotas`.`dueno_mascotas` (`id_dueno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_paseadorFK`
    FOREIGN KEY (`id_paseadorFK`)
    REFERENCES `Mascotas`.`paseadores` (`id_paseador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `id_duenoFK_idx` ON `Mascotas`.`paseadores_dueno_mascotas` (`id_duenoFK` ASC) VISIBLE;

CREATE INDEX `id_paseadorFK_idx` ON `Mascotas`.`paseadores_dueno_mascotas` (`id_paseadorFK` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Mascotas`.`info_mascotas_dueno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Mascotas`.`info_mascotas_dueno` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_duenoFK` INT NULL,
  `id_mascotaFK` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `id_duenoFK`
    FOREIGN KEY (`id_duenoFK`)
    REFERENCES `Mascotas`.`dueno_mascotas` (`id_dueno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_mascotasFK`
    FOREIGN KEY (`id_mascotaFK`)
    REFERENCES `Mascotas`.`info_mascotas` (`id_mascota`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `id_duenoFK_idx` ON `Mascotas`.`info_mascotas_dueno` (`id_duenoFK` ASC) VISIBLE;

CREATE INDEX `id_mascotasFK_idx` ON `Mascotas`.`info_mascotas_dueno` (`id_mascotaFK` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Mascotas`.`info_mascotas_veterinarias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Mascotas`.`info_mascotas_veterinarias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_veterinariaFK` INT NULL,
  `id_mascotaFK` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `id_veterinariaFK`
    FOREIGN KEY (`id_veterinariaFK`)
    REFERENCES `Mascotas`.`veterinarias` (`id_veterinaria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_mascotaFK`
    FOREIGN KEY (`id_mascotaFK`)
    REFERENCES `Mascotas`.`info_mascotas` (`id_mascota`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `id_veterinariaFK_idx` ON `Mascotas`.`info_mascotas_veterinarias` (`id_veterinariaFK` ASC) VISIBLE;

CREATE INDEX `id_mascotaFK_idx` ON `Mascotas`.`info_mascotas_veterinarias` (`id_mascotaFK` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Mascotas`.`info_mascotas_paseadores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Mascotas`.`info_mascotas_paseadores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_mascotaFK` INT NULL,
  `id_paseadorFK` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `id_mascotaFK`
    FOREIGN KEY (`id_mascotaFK`)
    REFERENCES `Mascotas`.`info_mascotas` (`id_mascota`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_paseadorFK`
    FOREIGN KEY (`id_paseadorFK`)
    REFERENCES `Mascotas`.`paseadores` (`id_paseador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `id_mascotaFK_idx` ON `Mascotas`.`info_mascotas_paseadores` (`id_mascotaFK` ASC) VISIBLE;

CREATE INDEX `id_paseadorFK_idx` ON `Mascotas`.`info_mascotas_paseadores` (`id_paseadorFK` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Mascotas`.`info_mascotas_peluquerias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Mascotas`.`info_mascotas_peluquerias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_peluqueriaFK` INT NULL,
  `id_mascotaFK` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `id_peluqueriaFK`
    FOREIGN KEY (`id_peluqueriaFK`)
    REFERENCES `Mascotas`.`peluquerias_caninas` (`id_peluqueria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_mascotaFK`
    FOREIGN KEY (`id_mascotaFK`)
    REFERENCES `Mascotas`.`info_mascotas` (`id_mascota`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `id_peluqueriaFK_idx` ON `Mascotas`.`info_mascotas_peluquerias` (`id_peluqueriaFK` ASC) VISIBLE;

CREATE INDEX `id_mascotaFK_idx` ON `Mascotas`.`info_mascotas_peluquerias` (`id_mascotaFK` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Mascotas`.`servicios_dueno_mascotas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Mascotas`.`servicios_dueno_mascotas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_duenoFK` INT NULL,
  `id_servicioFK` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `id_servicioFK`
    FOREIGN KEY (`id_servicioFK`)
    REFERENCES `Mascotas`.`servicios` (`id_servicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_duenoFK`
    FOREIGN KEY (`id_duenoFK`)
    REFERENCES `Mascotas`.`dueno_mascotas` (`id_dueno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `id_servicioFK_idx` ON `Mascotas`.`servicios_dueno_mascotas` (`id_servicioFK` ASC) VISIBLE;

CREATE INDEX `id_duenoFK_idx` ON `Mascotas`.`servicios_dueno_mascotas` (`id_duenoFK` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Mascotas`.`servicios_veterinarias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Mascotas`.`servicios_veterinarias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_servicioFK` INT NULL,
  `id_veterinariaFK` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `id_servicioFK`
    FOREIGN KEY (`id_servicioFK`)
    REFERENCES `Mascotas`.`servicios` (`id_servicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_veterinariaFK`
    FOREIGN KEY (`id_veterinariaFK`)
    REFERENCES `Mascotas`.`veterinarias` (`id_veterinaria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `id_servicioFK_idx` ON `Mascotas`.`servicios_veterinarias` (`id_servicioFK` ASC) VISIBLE;

CREATE INDEX `id_veterinariaFK_idx` ON `Mascotas`.`servicios_veterinarias` (`id_veterinariaFK` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Mascotas`.`servicios_paseadores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Mascotas`.`servicios_paseadores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_servicioFK` INT NULL,
  `id_paseadorFK` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `id_servicioFK`
    FOREIGN KEY (`id_servicioFK`)
    REFERENCES `Mascotas`.`servicios` (`id_servicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_paseadorFK`
    FOREIGN KEY (`id_paseadorFK`)
    REFERENCES `Mascotas`.`paseadores` (`id_paseador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `id_servicioFK_idx` ON `Mascotas`.`servicios_paseadores` (`id_servicioFK` ASC) VISIBLE;

CREATE INDEX `id_paseadorFK_idx` ON `Mascotas`.`servicios_paseadores` (`id_paseadorFK` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Mascotas`.`servicios_peluquerias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Mascotas`.`servicios_peluquerias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_servicioFK` INT NULL,
  `id_peluqueriaFK` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `id_servicioFK`
    FOREIGN KEY (`id_servicioFK`)
    REFERENCES `Mascotas`.`servicios` (`id_servicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_peluqueriaFK`
    FOREIGN KEY (`id_peluqueriaFK`)
    REFERENCES `Mascotas`.`peluquerias_caninas` (`id_peluqueria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `id_servicioFK_idx` ON `Mascotas`.`servicios_peluquerias` (`id_servicioFK` ASC) VISIBLE;

CREATE INDEX `id_peluqueriaFK_idx` ON `Mascotas`.`servicios_peluquerias` (`id_peluqueriaFK` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Mascotas`.`dueno_mascotas_grupos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Mascotas`.`dueno_mascotas_grupos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_duenoFK` INT NULL,
  `id_grupoFK` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `id_duenoFK`
    FOREIGN KEY (`id_duenoFK`)
    REFERENCES `Mascotas`.`dueno_mascotas` (`id_dueno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_grupoFK`
    FOREIGN KEY (`id_grupoFK`)
    REFERENCES `Mascotas`.`grupos` (`id_grupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `id_duenoFK_idx` ON `Mascotas`.`dueno_mascotas_grupos` (`id_duenoFK` ASC) VISIBLE;

CREATE INDEX `id_grupoFK_idx` ON `Mascotas`.`dueno_mascotas_grupos` (`id_grupoFK` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Mascotas`.`veterinarias_grupos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Mascotas`.`veterinarias_grupos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_veterinariaFK` INT NULL,
  `id_grupoFK` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `id_veterinariaFK`
    FOREIGN KEY (`id_veterinariaFK`)
    REFERENCES `Mascotas`.`veterinarias` (`id_veterinaria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_grupoFK`
    FOREIGN KEY (`id_grupoFK`)
    REFERENCES `Mascotas`.`grupos` (`id_grupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `id_veterinariaFK_idx` ON `Mascotas`.`veterinarias_grupos` (`id_veterinariaFK` ASC) VISIBLE;

CREATE INDEX `id_grupoFK_idx` ON `Mascotas`.`veterinarias_grupos` (`id_grupoFK` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Mascotas`.`paseadores_grupos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Mascotas`.`paseadores_grupos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_grupoFK` INT NULL,
  `id_paseadorFK` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `id_paseadorFK`
    FOREIGN KEY (`id_paseadorFK`)
    REFERENCES `Mascotas`.`paseadores` (`id_paseador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_grupoFK`
    FOREIGN KEY (`id_grupoFK`)
    REFERENCES `Mascotas`.`grupos` (`id_grupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `id_paseadorFK_idx` ON `Mascotas`.`paseadores_grupos` (`id_paseadorFK` ASC) VISIBLE;

CREATE INDEX `id_grupoFK_idx` ON `Mascotas`.`paseadores_grupos` (`id_grupoFK` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Mascotas`.`peluquerias_grupos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Mascotas`.`peluquerias_grupos` (
  `id` INT NOT NULL,
  `id_peluqueriaFK` INT NULL,
  `id_grupoFK` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `id_peluqueriaFK`
    FOREIGN KEY (`id_peluqueriaFK`)
    REFERENCES `Mascotas`.`peluquerias_caninas` (`id_peluqueria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_grupoFK`
    FOREIGN KEY (`id_grupoFK`)
    REFERENCES `Mascotas`.`grupos` (`id_grupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `id_peluqueriaFK_idx` ON `Mascotas`.`peluquerias_grupos` (`id_peluqueriaFK` ASC) VISIBLE;

CREATE INDEX `id_grupoFK_idx` ON `Mascotas`.`peluquerias_grupos` (`id_grupoFK` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
